Bootes.Web/Controllers/CorporatesController.cs
using Bootes.Core.Common;
using Bootes.Core.Domain.Enum;
using Bootes.Core.Domain.Form.Account;
using Bootes.Web.Helpers;
using System.Linq;
using System.Web.Mvc;

namespace Bootes.Web.Controllers
{
    public class CorporatesController : BaseController
    {
        [CustomAuth(Permissions = "SysAdmin")]
        public ActionResult Index(string name = "", string code = "", int countryId = 0, string regId = "", string publicName = "", int appId = 0, string act = "")
        {
            if (act.ToLower() == "export")
            {
                var data = Logic.CorporateService.SearchView(name, code, countryId, regId, publicName, appId, page: 0);
                Download(data);
            }
            ViewBag.Apps = Util.SerializeJSON(Logic.AppService.Search().ToList().ShapeList("Id,Name"));
            return View();
        }
         
        public ActionResult GettingStarted(int id)
        {
            ViewBag.Form = Util.SerializeJSON(Logic.FactoryModule.Corporates.DefaultForm());
            ViewBag.Countries = Util.SerializeJSON(Logic.LocationService.SearchView(locationTypeId: 2, sort: "Name", page: 0)
                .Items.ShapeList("Id,Name"));
            return View();
        }

        [HttpPost]
        public ActionResult GettingStarted(int id, CorporateForm form)
        {
            ViewBag.Countries = Util.SerializeJSON(Logic.LocationService.SearchView(locationTypeId: 2, sort: "Name", page: 0)
                .Items.ShapeList("Id,Name"));
            ViewBag.Form = Util.SerializeJSON(form);
            if (!ModelState.IsValid)
            {
                AlertDanger(ModelError(ModelState));
                return View();
            }

            //for now users can only create one merchnat

            var msg = "";
            msg = Logic.CorporateService.ValidateSignUp(form);
            if (!string.IsNullOrEmpty(msg))
            {
                AlertDanger(msg);
                return View();
            }
            var code = "";
            var signupStatus = Logic.CorporateService.SignUp(form, LoggedInUser.User, out code);
            switch (signupStatus)
            {
                case SignUpStatus.Ok:
                    msg = "Sign up was successful!";
                    break;
                case SignUpStatus.MobileExists:
                    msg = "Account already exists, please reset your account";
                    break;
            }
            if (signupStatus != SignUpStatus.Ok)
            {
                AlertDanger(msg);
                return View();
            }
            AlertSuccess(msg);
            return RedirectToAction("Update", new { Id = code });
        }

        [HttpGet]
        [CustomAuth(Permissions = "Subscriber")]
        public ActionResult Update(string id)
        {
            //get corporate by code
            var corporate = Logic.CorporateService.SearchView(code: id).Items.FirstOrDefault();
            if (corporate == null)
            {
                AlertWarning("Invalid corporate code");
                return RedirectToAction("Home");
            }

            var corpForm = Logic.FactoryModule.Corporates.CreateFrom(corporate);
            var tags = Logic.TagService.SearchView("merchant", corpForm.Id).Items; 
            corpForm.Tags = string.Join(",", tags.Select(x => x.TagName).ToArray());
            ViewBag.Form = Util.SerializeJSON(corpForm); 
            ViewBag.Countries = Util.SerializeJSON(Logic.LocationService.SearchView(locationTypeId: 2, sort: "Name", page: 0)
                .Items.ShapeList("Id,Name"));
            ViewBag.MerchantName = corpForm.PublicName;
            return View();
        }

        [HttpGet]
        [CustomAuth(Permissions = "Subscriber")]
        public ActionResult Home()
        {
            ViewBag.UserId = LoggedInUser.User.Id;
            return View();
        }

        [HttpGet]
        [CustomAuth(Permissions = "SysAdmin")]
        public ActionResult ApproveList()
        {
            return View();
        }

        [HttpGet]
        [CustomAuth(Permissions = "SysAdmin")]
        public ActionResult Approve(string id)
        {
            //get corporate by code
            var corporate = Logic.CorporateService.SearchView(code: id, corporatestatus: 1).Items.FirstOrDefault();
            if (corporate == null)
            {
                AlertWarning("Invalid corporate code");
                return RedirectToAction("Home");
            }
            var corpForm = new CorporateApprovalForm()
            {
                CorporateId = corporate.Id
            };

            ViewBag.Model = Util.SerializeJSON(corporate);
            ViewBag.Form = Util.SerializeJSON(corpForm);
            return View();
        }

    }
}

Bootes.Web/Controllers/MerchantsController.cs
using Bootes.Core.Common;
using Bootes.Web.Helpers;
using System.Linq;
using System.Web.Mvc;

namespace Bootes.Web.Controllers
{
    public class MerchantsController : BaseController
    {

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [CustomAuth(Permissions = "Merchant")]
        public ActionResult Home(string id)
        {
            var corporate = Logic.CorporateService.SearchView(code: id, corporatestatus: 2, page: 0).Items.FirstOrDefault();
            if (corporate == null)
            {
                AlertWarning("Invalid corporate code");
                return RedirectToAction("Index");
            }

            if (!LoggedInUser.UserInCorporate(corporate.Id))
            {
                AlertWarning("Invalid Access");
                return RedirectToAction("Index");
            }


            ViewBag.Corporate = Util.SerializeJSON(corporate);
            ViewBag.CorporateId = corporate.Id;

            var wallets = Logic.WalletService.SearchView(walletTypeId: 2, ownerId: corporate.Id, page: 0).Items;

            if (wallets == null)
            {
                var wallet = Logic.WalletService.CreateMerchantWallet(corporate);
                wallets.Add(wallet);
            }
            if (wallets.Count <= 0)
            {
                var wallet = Logic.WalletService.CreateMerchantWallet(corporate);
                wallets.Add(wallet);
            }
            ViewBag.Wallets = Util.SerializeJSON(wallets);

            ViewBag.MerchantName = corporate.PublicName;

            return View();
        }
    }
}

Bootes.Web/Controllers/WalletsController.cs
using Bootes.Core.Common;
using Bootes.Core.Domain.Helper;
using Bootes.Web.Helpers;
using System.Linq;
using System.Web.Mvc;

namespace Bootes.Web.Controllers
{
    public class WalletsController : BaseController
    {

        [CustomAuth(Permissions = "SysAdmin")]
        public ActionResult Index(string name = "", string code = "", int walletTypeId = 0, decimal currentBalance = 0, decimal openingBalance = 0, decimal balanceLimit = 0, decimal heldBalance = 0, int currencyId = 0, int ownerId = 0, string act = "")
        {
            if (act.ToLower() == "export")
            {
                var data = Logic.WalletService.SearchView(name, code, walletTypeId, currentBalance, openingBalance, balanceLimit, heldBalance, currencyId, ownerId, page: 0);
                Download(data);
            }
            return View();
        }

        [CustomAuth(Permissions = "Merchant")]
        public ActionResult Fund(string id)
        {
            //get wallet
            var wallet = Logic.WalletService.SearchView(code: id, page: 0).Items.FirstOrDefault();
            if (wallet == null)
            {
                return HttpNotFound("Invalid Wallet");
            }

            if (!LoggedInUser.UserInCorporate(wallet.OwnerId))
            {
                AlertWarning("Invalid Access");
                return RedirectToAction("Index");
            }
            //create wallet fund model
            var form = Logic.FactoryModule.WalletTransacts.WalletFund(wallet, LoggedInUser.User);

            var settings = Logic.EntitySettingService.SearchView(entityType: "RAVE", entityRef: Constants.RAVE_ID).Items;
            var eshelper = new EntitySettingHelper(settings);
            form.PublicKey = eshelper.GetValue("PUBLIC_KEY");
            ViewBag.Wallet = Util.SerializeJSON(wallet);
            ViewBag.WalletFund = Util.SerializeJSON(form);
            ViewBag.RaveJS = eshelper.GetValue("GATEWAY_URL");
            return View();
        }

        [CustomAuth(Permissions = "Merchant")]
        public ActionResult Withdraw(string id)
        {
            return View();
        }

        public ActionResult Statement(string id)
        {
            var wallet = Logic.WalletService.SearchView(code: id, page: 0).Items.FirstOrDefault();
            if (wallet == null)
            {
                return HttpNotFound("Invalid Wallet");
            }
            if (wallet.WalletTypeId == 2)
            {
                if (!LoggedInUser.UserInCorporate(wallet.OwnerId))
                {
                    AlertWarning("Invalid Access");
                    return RedirectToAction("Index");
                }
            }

            if(wallet.WalletTypeId == 3)
            {
                if (LoggedInUser.User.Id != wallet.OwnerId)
                {
                    AlertWarning("Invalid Access");
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Wallet = Util.SerializeJSON(wallet);
            return View();
        }
         

    }
}

Bootes.Web/Views/Wallets/Fund.cshtml
@{
    ViewBag.Title = "Fund Wallet";
}

@section styles
{

}
<div id="appView">
    <div class="row">
        <div class="col-md-8">

            <div class="card-group">
                <div class="card  bg-light">
                    <div class="card-body">
                        <div class="d-flex align-items-center">
                            <div class="m-r-10">
                                <img src="~/dist/img/2.jpg" alt="user" width="60" class="rounded-circle">
                            </div>
                            <div>
                                <h3 class="m-b-0"><span v-html="wallet.Name"></span></h3>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 text-right">
                                <h3><span v-html="wallet.CurrencyName"></span> <span v-html="formatPrice(wallet.CurrentBalance)"></span> </h3>
                                <h6 class="card-subtitle"> <span v-html="wallet.WalletTypeName"></span></h6>

                                <div>
                                    <a :href="_baseurl + '/Wallets/Fund/' + wallet.Code" class="btn btn-sm btn-success waves-effect waves-light"
                                       data-toggle="tooltip" data-original-title="Fund"><i class="ti-plus"></i></a>
                                    <a :href="_baseurl + '/Wallets/Withdraw/' + wallet.Code" class="btn btn-sm btn-secondary waves-effect waves-light"
                                       data-toggle="tooltip" data-original-title="Withdraw">
                                        <i class="ti-minus"></i>
                                    </a>
                                    <a :href="_baseurl + '/Wallets/Statement/' + wallet.Code" class="btn btn-sm btn-info waves-effect waves-light"
                                       data-toggle="tooltip" data-original-title="Statement">
                                        <i class="ti-menu-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>





            </div>





            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <form method="post" autocomplete="off" @@submit.prevent="justHoldIt">
                            <div class="form-body">
                                <div class="card-body">
                                    <div class="row p-t-20">
                                        <div class="col-md-6">
                                            <div class="form-group has-danger">
                                                <label class="control-label">Receipt Email</label>
                                                <input type="text" id="Email" name="Email" class="form-control" v-model="form.Email" :readonly="showConsent">
                                                <small class="form-control-feedback"> Email address to receive receipt </small>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group has-danger">
                                                <label class="control-label">Remarks</label>
                                                <input type="text" id="Remarks" name="Remarks" class="form-control" v-model="form.Remarks" :readonly="showConsent">
                                                <small class="form-control-feedback"> Remarks for transaction </small>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label">Amount</label>
                                                <input type="text" id="Amount" name="Amount" class="form-control" v-model="form.Amount" :readonly="showConsent">
                                                <small class="form-control-feedback">Amount to fund in NGN? </small>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label">Payment Reference</label>
                                                <input type="text" id="PaymentReference" name="PaymentReference" class="form-control" v-model="form.PaymentReference" :readonly="showConsent">
                                                <small class="form-control-feedback">Your Custom reference </small>
                                            </div>
                                        </div>
                                        <div class="col-md-6" v-if="showConsent">
                                            <div class="form-group has-danger">
                                                <label class="control-label">Transaction Source</label>
                                                <input type="text" id="SourceId" name="SourceId" class="form-control" v-model="form.SourceId" :readonly="showConsent">
                                                <small class="form-control-feedback"> Information </small>
                                            </div>
                                        </div>
                                        <div class="col-md-6" v-if="showConsent">
                                            <div class="form-group has-danger">
                                                <label class="control-label">Transaction Reference</label>
                                                <input type="text" id="TxId" name="TxId" class="form-control" v-model="form.TxId" :readonly="showConsent">
                                                <small class="form-control-feedback"> Please take note of this </small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <div class="card-body">
                                        <button type="button" class="btn btn-info" v-if="!showConsent" v-on:click="PreProcess"> <i class="fa fa-play"></i> Proceed</button>
                                        <button type="submit" class="btn btn-success" v-if="showConsent" v-on:click="ForwardPayment"> <i class="fa fa-check"></i> Pay</button>
                                        <button type="button" class="btn btn-danger" v-if="showConsent" v-on:click="CancelPayment"> <i class="fa fa-stop"></i> Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>


                </div>


            </div>
        </div>
        <div class="col-md-4">

            <div class="card bg-white">
                <div class="card-body">
                    <h3><i class="ti-direction-alt font-20"></i>  Merchant Sign up</h3>
                    <p>Create your merchant account</p>
                    <div>
                        <a href="@Url.Action("GettingStarted","Corporates", new { id = "1" })" class="btn btn-sm btn-info waves-effect waves-light">Get Started</a>

                        <a href="@Url.Action("Index","Merchants")" class="btn btn-sm btn-secondary waves-effect waves-light">See Available Merchants</a>
                    </div>
                </div>




            </div>
             
        </div>
    </div>
</div>



@section scripts
{
     
    <script type="text/javascript" src="@Html.Raw(ViewBag.RaveJS)"></script> 
    <script type="text/javascript">
        var Wallet = @Html.Raw(ViewBag.Wallet);
        var WalletFund = @Html.Raw(ViewBag.WalletFund);
        var pageApp = new Vue({
            el: '#appView',
            data: {
                wallet: Wallet, 
                form: WalletFund,
                showConsent: false
            },
            methods: {
                formatPrice: function (value) {
                    return SiteUtil.formatPrice(value);
                },
                PreProcess: function () {
                    //this is where I call Rave API
                    var n = new Number(pageApp.form.Amount);
                    if (isNaN(n)) {
                        ShowLoading("Invalid Amount.", "warning");
                        pageApp.form.Amount = 0;
                        return 1;
                    }
                    if (n < 0.01) {
                        ShowLoading("Invalid Amount..", "warning");
                        pageApp.form.Amount = 0;
                        return 1;
                    } 
                    var req = TransactDataUtil.InitiateFund(pageApp.form);
                    req.done(function (data) {
                        pageApp.form.TxId = data.TxId;  
                        pageApp.showConsent = true; 
                    });
                    req.fail(function (data) {
                        ShowLoading("could not initiate transaction", "error");
                    });
                    return 1;
                },
                ForwardPayment: function () {
                    //flag payment before opening gateway
                    var req = TransactDataUtil.ForwardPayment(pageApp.form);
                    req.done(function (data) {
                        TransactDataUtil.CallGateway(pageApp.form, "Fund " + pageApp.wallet.Name);
                    });
                    req.fail(function (data) {
                        ShowLoading("could not forward transaction: " + JSON.stringify(data), "error");
                    });
                    return 1;
                },
                CancelPayment: function () {
                    var req = TransactDataUtil.CancelPayment(pageApp.form.TxId);
                    req.done(function (data) {
                        ShowLoading("Payment has been cancelled!");
                        window.location = _baseurl + '/Transactions/Revalidate/' + pageApp.form.TxId;  
                    });
                    req.fail(function (data) {
                        ShowLoading("could not cancel transaction", "error");
                    });
                    return 1;
                },
                justHoldIt: function () {
                    return 1;
                }
            }
        });

    </script>
}

Bootes.Web/Views/Wallets/FundValidate.cshtml
@{
    ViewBag.Title = "FundValidate";
}

<h2>FundValidate</h2>

Bootes.Web/Views/Wallets/Statement.cshtml
@{
    ViewBag.Title = "Statement";
    string sim = Bootes.Core.Common.Constants.API_URL;
}

<div id="appView">
    <div class="row">
        <div class="col-12">
            <table id="grid" class="table table-hover" style="width:100%; font-size:0.8em;">
                <thead>
                    <tr>
                        <th>Value Date</th>
                        <th>Source</th>
                        <th>Type</th>
                        <th>PayRef</th>
                        <th>Narration</th>
                        <th>Dr/Cr</th>
                        <th>Credit</th>
                        <th>Debit</th>
                        <th>Balance BF</th>
                        <th>Transactions</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
    <h2></h2>




</div>



@section scripts
{
    <script type="text/javascript">
        var wallet = @Html.Raw(ViewBag.Wallet);
        $(document).ready(function () {
             
            var _columns = [
                {
                    "data": "ValueDate",
                    "className": 'd-none d-sm-table-cell',
                    "render": function (data, type, row, meta) {
                        return SiteUtil.formatDate(data, 1);
                    }
                },
                {
                    "data": "SourceId",
                    "className": 'd-none d-sm-table-cell' },
                {
                    "data": "TransactCodeName",
                    "className": 'd-none d-sm-table-cell' },
                {
                    "data": "PaymentReferenceText",
                    "className": 'd-none d-sm-table-cell',
                    "render": function (data, type, row, meta) {
                        return '<samp>' + data + '</samp>';
                    }
                },
                {
                    "data": "Narration",
                    "className": 'd-none d-sm-table-cell' 
                },
                {
                    "data": "DrCrText",
                    "className": 'd-none d-sm-table-cell',
                    "render": function (data, type, row, meta) {
                        return '<span class="label ' + SiteUtil.formatLabel(row.DrCrText) + '">' + data + '</span>';
                    }
                },
                {
                    "data": "Amount",
                    "className": 'text-right d-none d-sm-table-cell',
                    "render": function (data, type, row, meta) {
                        if (row.DrCr == 2) {
                            return '<samp>' + SiteUtil.formatPrice(data) + '</samp>';
                        }
                        else {
                            return ' ';
                        }
                    }
                },
                {
                    "data": "Amount",
                    "className": 'text-right d-none d-sm-table-cell',
                    "render": function (data, type, row, meta) {
                        if (row.DrCr == 1) {
                            return '<samp>' + SiteUtil.formatPrice(data) + '</samp>';
                        }
                        else {
                            return ' ';
                        }
                    }
                },
                {
                    "data": "CurrentBalanceBF",
                    "className": 'text-right d-none d-sm-table-cell',
                    "render": function (data, type, row, meta) {
                        return '<samp>' + SiteUtil.formatPrice(data) + '</samp>';
                    }
                },
                {
                    "data": "Id",
                    "className": 'd-block d-sm-none',
                    "render": function (data, type, row, meta) {
                        return '<div class="d-flex flex-row comment-row m-t-0"><div class="w-100"><span class="m-b-0 d-block">' + row.Narration
                            + '  </span> <div class="comment-footer"><span class="float-right">'
                            + row.CurrencyName + ' ' + SiteUtil.formatPrice(row.Amount)
                            + '</span > <span class="float-right">&nbsp;</span> <span class="float-right label '
                            + SiteUtil.formatLabel(row.DrCrText) + '">' + row.DrCrText
                            + '</span> <span>' + SiteUtil.formatDate(row.ValueDate, 1) + '</span></div ></div ></div>';
                    }
                }
            ];

            var _row = {
                "createdRow": function (row, data, index) {
                    //if (data.DrCr === 2) {
                    //    $(row).addClass("label-warning");
                    //}
                }
            } 

            FormUtil.Grid({
                entity: 'MyChange/WalletStatements',
                url: '@sim',
                columns: _columns,
                row: _row,
                table: 'grid',
                query: "WalletId=" + wallet.Id
            });
        });
    </script>
}

Bootes.Web/Views/Wallets/Withdraw.cshtml
@{
    ViewBag.Title = "Withdraw";
}

<h2>Withdraw</h2>