Bootes.Web/Controllers/AppsController.cs
using Bootes.Core.Common;
using Bootes.Web.Helpers;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Bootes.Web.Controllers
{

    public class AppsController : BaseController
    {
        [CustomAuth(Permissions = "SysAdmin")]
        public ActionResult Index(string name = "", string code = "", int? runtimeStatusId = 0, DateTime? availableAt = null, string act = "")
        {
            if (act.ToLower() == "export")
            {
                var data = Logic.AppService.SearchView(name, code, runtimeStatusId.GetValueOrDefault(), availableAt, page: 0);
                Download(data);
            }
            ViewBag.RuntimeStatus = Util.SerializeJSON(Logic.EntitySettingService.SelectList("RUNTIMESTATUS").ToList());
            return View();
        }
    }


}

Bootes.Web/Controllers/ArticlesController.cs
using Bootes.Web.Helpers;
using System.Web.Mvc;

namespace Bootes.Web.Controllers
{
    public class ArticlesController : BaseController
    {
        [CustomAuth(Permissions = "SysAdmin")]
        public ActionResult Index(string name = "", string title = "", string tags = "",
            string content = "", int editorType = 0, string altContents = "", string act = "")
        {
            if (act.ToLower() == "export")
            {
                var data = Logic.ArticleService.SearchView(name, title, tags, content, editorType, altContents, page: 0);
                Download(data);
            }
            return View();
        }
    }


}

Bootes.Web/Controllers/UsersController.cs
using Bootes.Core.Common;
using Bootes.Core.Domain.Enum;
using Bootes.Core.Domain.Form.Account;
using Bootes.Web.Helpers;
using System.Linq;
using System.Web.Mvc;

namespace Bootes.Web.Controllers
{
public class UsersController : BaseController
    {

        [HttpGet]
        [CustomAuth(Permissions = "Merchant")]
        public ActionResult Admins(string id)
        {
            var corporate = Logic.CorporateService.SearchView(code: id, corporatestatus: 2, page: 0).Items.FirstOrDefault();
            if (corporate == null)
            {
                AlertWarning("Invalid corporate code");
                return RedirectToAction("Index");
            }

            if (!LoggedInUser.UserInCorporate(corporate.Id))
            {
                AlertWarning("Invalid Access");
                return RedirectToAction("Index");
            }


            ViewBag.Corporate = Util.SerializeJSON(corporate);
            ViewBag.CorporateId = corporate.Id;
            ViewBag.CorporateName = corporate.PublicName;
            ViewBag.CorporateRoles = Util.SerializeJSON(Logic
               .CorporateRoleService.SearchView(corporateId: corporate.Id , page: 0)
               .Items.ShapeList("Id,Name"));
            ViewBag.UserStatuses = Util.SerializeJSON(Logic.EntitySettingService.SelectList("USERSTATUS").ToList());
             
            return View();
        }
    }
}

Bootes.Web/Controllers/WalletsController.cs
using Bootes.Core.Common;
using Bootes.Core.Domain.Helper;
using Bootes.Web.Helpers;
using System.Linq;
using System.Web.Mvc;

namespace Bootes.Web.Controllers
{
    public class WalletsController : BaseController
    {

        [CustomAuth(Permissions = "SysAdmin")]
        public ActionResult Index(string name = "", string code = "", int walletTypeId = 0, decimal currentBalance = 0, decimal openingBalance = 0, decimal balanceLimit = 0, decimal heldBalance = 0, int currencyId = 0, int ownerId = 0, string act = "")
        {
            if (act.ToLower() == "export")
            {
                var data = Logic.WalletService.SearchView(name, code, walletTypeId, currentBalance, openingBalance, balanceLimit, heldBalance, currencyId, ownerId, page: 0);
                Download(data);
            }
            return View();
        }

        [CustomAuth(Permissions = "Merchant")]
        public ActionResult Fund(string id)
        {
            //get wallet
            var wallet = Logic.WalletService.SearchView(code: id, page: 0).Items.FirstOrDefault();
            if (wallet == null)
            {
                return HttpNotFound("Invalid Wallet");
            }

            if (!LoggedInUser.UserInCorporate(wallet.OwnerId))
            {
                AlertWarning("Invalid Access");
                return RedirectToAction("Index");
            }
            //create wallet fund model
            var form = Logic.FactoryModule.WalletTransacts.WalletFund(wallet, LoggedInUser.User);

            var settings = Logic.EntitySettingService.SearchView(entityType: "RAVE", entityRef: Constants.RAVE_ID).Items;
            var eshelper = new EntitySettingHelper(settings);
            form.PublicKey = eshelper.GetValue("PUBLIC_KEY");
            ViewBag.Wallet = Util.SerializeJSON(wallet);
            ViewBag.WalletFund = Util.SerializeJSON(form);
            ViewBag.RaveJS = eshelper.GetValue("GATEWAY_URL");
            return View();
        }

        [CustomAuth(Permissions = "Merchant")]
        public ActionResult Withdraw(string id)
        {
            return View();
        }

        public ActionResult Statement(string id)
        {
            var wallet = Logic.WalletService.SearchView(code: id, page: 0).Items.FirstOrDefault();
            if (wallet == null)
            {
                return HttpNotFound("Invalid Wallet");
            }
            if (wallet.WalletTypeId == 2)
            {
                if (!LoggedInUser.UserInCorporate(wallet.OwnerId))
                {
                    AlertWarning("Invalid Access");
                    return RedirectToAction("Index");
                }
            }

            if(wallet.WalletTypeId == 3)
            {
                if (LoggedInUser.User.Id != wallet.OwnerId)
                {
                    AlertWarning("Invalid Access");
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Wallet = Util.SerializeJSON(wallet);
            return View();
        }
         

    }
}

Bootes.Web/Views/Shared/_LayoutSite.cshtml
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title - MyChange</title>
    <link href="~/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet" type="text/css">
    <link href="~/assets/libs/toastr/build/toastr.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/libs/select2/dist/css/select2.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="~/assets/libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <link href="~/dist/css/style.min.css" rel="stylesheet">
    <link href="~/dist/css/Site.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    @RenderSection("styles", required: false)
</head>
<body>
    @{
        string _baseurl = Bootes.Core.Common.Constants.SITE_URL;
        string _baseapi = Bootes.Core.Common.Constants.API_URL;
    }
    <script type="text/javascript">
        var _baseurl = '@_baseurl';
        var _baseapi = '@_baseapi';
    </script>
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <div id="main-wrapper">
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header">
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)">
                        <i class="ti-menu ti-close"></i>
                    </a>
                    <a class="navbar-brand" href="@Url.Action("Index","Home")">
                        <b class="logo-icon">
                            <img src="~/assets/images/logo-icon.png" alt="homepage" class="dark-logo" />
                            <img src="~/assets/images/logo-light-icon.png" alt="homepage" class="light-logo" />
                        </b>
                        <span class="logo-text">
                            <img src="~/assets/images/logo-text.png" alt="homepage" class="dark-logo" />
                            <img src="~/assets/images/logo-light-text.png" class="light-logo" alt="homepage" />
                        </span>
                    </a>
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent"
                       aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="ti-more"></i>
                    </a>
                </div>
                <div class="navbar-collapse collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav float-left mr-auto">
                        <li class="nav-item d-none d-md-block">
                            <a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar">
                                <i class="sl-icon-menu font-20"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav float-right">
                        @*<li class="nav-item search-box">
                            <a class="nav-link waves-effect waves-dark" href="javascript:void(0)">
                                <i class="ti-search font-16"></i>
                            </a>
                            <form class="app-search position-absolute">
                                <input type="text" class="form-control" placeholder="Search &amp; enter">
                                <a class="srh-btn">
                                    <i class="ti-close"></i>
                                </a>
                            </form>
                        </li>*@
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">
                                <img src="~/dist/img/1.jpg" alt="user" class="rounded-circle" width="31">
                            </a>
                            <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                                @if (Request.IsAuthenticated)
                                {
                                    <a class="dropdown-item" href="@Url.Action("Index","Dashboard")">
                                        <i class="ti-dashboard m-r-5 m-l-5"></i> My Dashboard
                                    </a>
                                    <a class="dropdown-item" href="@Url.Action("LogOff","Accounts")">
                                        <i class="ti-lock m-r-5 m-l-5"></i> Sign Out
                                    </a>
                                }
                                else
                                {
                                    <a class="dropdown-item" href="@Url.Action("SignUp","Accounts")">
                                        <i class="ti-plus m-r-5 m-l-5"></i> Sign Up
                                    </a>
                                    <a class="dropdown-item" href="@Url.Action("SignIn","Accounts")">
                                        <i class="ti-user m-r-5 m-l-5"></i> Sign In
                                    </a>

                                }
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="left-sidebar">
            <div class="scroll-sidebar">
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        @*<li class="nav-small-cap"> <span class="hide-menu">Menu</span></li>*@
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark" href="@Url.Action("Index","Home")" aria-expanded="false"><span class="hide-menu">Home </span></a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark" href="@Url.Action("Page","Home", new { @Id = "Howitworks" })" aria-expanded="false"><span class="hide-menu">How It Works</span></a>
                        </li> 
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark" href="@Url.Action("Page","Home", new { @Id = "Merchants" })" aria-expanded="false"><span class="hide-menu">Our Merchants</span></a>
                        </li> 
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark" href="@Url.Action("Page","Home", new { @Id = "Devs" })" aria-expanded="false"><span class="hide-menu">Developers</span></a>
                        </li>
                        @*<li class="sidebar-item">
            <a class="sidebar-link has-arrow waves-effect waves-dark" href="@Url.Action("Page","Home", new { @Id = "geeks" })" aria-expanded="false"><span class="hide-menu">Developers </span></a>
            <ul aria-expanded="false" class="collapse  first-level">
                <li class="sidebar-item"><a href="javascript:void(0)" class="sidebar-link"><i class="mdi mdi-adjust"></i><span class="hide-menu"> API Documentation</span></a></li>
                <li class="sidebar-item"><a href="javascript:void(0)" class="sidebar-link"><i class="mdi mdi-adjust"></i><span class="hide-menu"> Request Help </span></a></li>
            </ul>
        </li>*@
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark" href="@Url.Action("Page","Home", new { @Id = "Features" })" aria-expanded="false"><span class="hide-menu">Features</span></a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark" href="@Url.Action("Page","Home", new { @Id = "About" })" aria-expanded="false"><span class="hide-menu">About Us</span></a>
                        </li>

                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark" href="@Url.Action("Page","Home", new { @Id = "Contact" })" aria-expanded="false"><span class="hide-menu">Contact </span></a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>

        <footer class="footer text-right">

            mychange &copy; 2019
        </footer>
    </div>
    <div class="chat-windows"></div>
    <script src="~/assets/libs/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- apps -->
    <script src="~/dist/js/app.min.js"></script>
    <script src="~/dist/js/app.init.boxed.js"></script>
    <script src="~/dist/js/app-style-switcher.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="~/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/assets/extra-libs/sparkline/sparkline.js"></script>
    <!--Wave Effects -->
    <script src="~/dist/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="~/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/dist/js/custom.min.js"></script>
    <script src="~/assets/extra-libs/DataTables/datatables.min.js"></script>
    <script src="~/assets/libs/toastr/build/toastr.min.js"></script>
    <script src="~/assets/libs/select2/dist/js/select2.full.min.js"></script>
    <script src="~/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="~/dist/js/vue.js"></script>
    <script src="~/dist/js/Site.js"></script>
    <script src="~/dist/js/Site.app.js"></script>

    @RenderSection("scripts", required: false)
    @Html.Partial("_PartialAlert")
</body>
</html>

Bootes.Web/Views/Shared/_PartialAlert.cshtml
@{
    var alerts = TempData.ContainsKey(Bootes.Core.UI.Alert.TempDataKey)
                ? (List<Bootes.Core.UI.Alert>)TempData[Bootes.Core.UI.Alert.TempDataKey]
                : new List<Bootes.Core.UI.Alert>();


    foreach (var alert in alerts)
    {
        @*var dismissableClass = alert.Dismissable ? "alert-dismissable" : null;
            <div class="alert alert-@alert.AlertStyle @dismissableClass">
                @if (alert.Dismissable)
                {
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                }
                @Html.Raw(alert.Message)
            </div>*@

        <script type="text/javascript">
                    $(document).ready(function () {
                        ShowLoading('@Html.Raw(alert.Message)', '@alert.AlertStyle');
                    });
        </script>

    }

}

Bootes.Web/Views/Shared/_PartialMenu.cshtml
@model List<string>

<li class="sidebar-item">
    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Index","Dashboard")" aria-expanded="false">
        <i class="sl-icon-loop"></i>
        <span class="hide-menu">My Dashboard</span>
    </a>
</li>



@if (Model.Contains("SysAdmin"))
{
    <li class="sidebar-item">
        <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)
                                   " aria-expanded="false">
            <i class="mdi mdi-notification-clear-all"></i>
            <span class="hide-menu">Site Admin</span>
        </a>


        <ul aria-expanded="false" class="collapse first-level">
            <li class="sidebar-item">
                <a href="@Url.Action("Index", "Apps")" class="sidebar-link">
                    <i class="mdi mdi-octagram"></i>
                    <span class="hide-menu">Apps</span>
                </a>
            </li>
            <li class="sidebar-item">
                <a href="@Url.Action("Index", "EntitySettings")" class="sidebar-link">
                    <i class="mdi mdi-octagram"></i>
                    <span class="hide-menu">Settings</span>
                </a>
            </li>

            <li class="sidebar-item">
                <a href="@Url.Action("Index", "Corporates")" class="sidebar-link">
                    <i class="mdi mdi-playlist-check"></i>
                    <span class="hide-menu">Corporates</span>
                </a>
            </li>

            <li class="sidebar-item">
                <a href="@Url.Action("Index", "CorporateRoles")" class="sidebar-link">
                    <i class="mdi mdi-playlist-check"></i>
                    <span class="hide-menu">Roles</span>
                </a>
            </li>

            <li class="sidebar-item">
                <a href="@Url.Action("Index", "SiteUsers")" class="sidebar-link">
                    <i class="mdi mdi-playlist-check"></i>
                    <span class="hide-menu">Users</span>
                </a>
            </li>

            <li class="sidebar-item">
                <a href="@Url.Action("Index", "Locations")" class="sidebar-link">
                    <i class="mdi mdi-playlist-check"></i>
                    <span class="hide-menu">Locations</span>
                </a>
            </li>
            <li class="sidebar-item">
                <a href="@Url.Action("Index", "Wallets")" class="sidebar-link">
                    <i class="mdi mdi-playlist-check"></i>
                    <span class="hide-menu">Wallets</span>
                </a>
            </li>

        </ul>

    </li>

    <li class="sidebar-item">
        <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)
                                   " aria-expanded="false">
            <i class="mdi mdi-notification-clear-all"></i>
            <span class="hide-menu">Content</span>
        </a>
        <ul aria-expanded="false" class="collapse first-level">

            <li class="sidebar-item">
                <a href="@Url.Action("Index", "Articles")" class="sidebar-link">
                    <i class="mdi mdi-playlist-check"></i>
                    <span class="hide-menu">Articles</span>
                </a>
            </li>
            <li class="sidebar-item">
                <a href="@Url.Action("Index", "OutBoxes")" class="sidebar-link">
                    <i class="mdi mdi-playlist-check"></i>
                    <span class="hide-menu">OutBoxes</span>
                </a>
            </li>
        </ul>
    </li>

    <li class="sidebar-item">
        <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0) " aria-expanded="false">
            <i class="mdi mdi-notification-clear-all"></i>
            <span class="hide-menu">Merchants Admin</span>
        </a>
        <ul aria-expanded="false" class="collapse first-level">


            <li class="sidebar-item">
                <a href="@Url.Action("ApproveList", "Corporates")" class="sidebar-link">
                    <i class="mdi mdi-playlist-check"></i>
                    <span class="hide-menu">Approve/Reject</span>
                </a>
            </li>
        </ul>
    </li>
}

@if (Model.Contains("Merchant"))
{
    <li class="sidebar-item">
        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Home", "Corporates")" aria-expanded="false">
            <i class="icon-Shop-4"></i>
            <span class="hide-menu">List Merchants</span>
        </a>
    </li>

    @*<li class="sidebar-item">
        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="@Url.Action("Admins", "Users")" aria-expanded="false">
            <i class="icon-Talk-Man"></i>
            <span class="hide-menu">List Users</span>
        </a>
    </li>*@

}